# Generated by Django 3.2.15 on 2022-08-18 18:42

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("eawork", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpostversion",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="eawork.jobpost",
            ),
        ),
    ]
