# Generated by Django 3.2.15 on 2022-08-22 15:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("eawork", "0004_add_more_job_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="career_page_url",
            field=models.URLField(blank=True, max_length=511),
        ),
        migrations.AddField(
            model_name="company",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="company",
            name="id_external_80_000_hours",
            field=models.CharField(blank=True, max_length=511),
        ),
        migrations.AddField(
            model_name="company",
            name="logo_url",
            field=models.URLField(blank=True, max_length=511),
        ),
        migrations.AddField(
            model_name="company",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="company",
            name="url",
            field=models.URLField(blank=True, max_length=511),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="eawork.company",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="facebook_url",
            field=models.URLField(blank=True, max_length=511, verbose_name="Facebook"),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="company",
            name="linkedin_url",
            field=models.URLField(blank=True, max_length=511, verbose_name="Linkedin"),
        ),
    ]
