# Generated by Django 3.2.15 on 2022-08-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eawork", "0006_add_model_job_alert"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobalert",
            name="query",
        ),
        migrations.RemoveField(
            model_name="jobalert",
            name="query_raw",
        ),
        migrations.AddField(
            model_name="jobalert",
            name="query_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobalert",
            name="query_string",
            field=models.URLField(blank=True, max_length=1023),
        ),
    ]
