# Generated by Django 3.2.15 on 2022-08-23 18:24

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eawork", "0007_rename_job_alert_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobalert",
            name="jobs_seen",
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
