# Generated by Django 3.2.15 on 2022-08-25 19:32

import enumfields.fields
from django.db import migrations
from django.db.models import TextField

import eawork.models.post


class Migration(migrations.Migration):

    dependencies = [
        ("eawork", "0008_alter_field_job_alert_jobs_seen"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobpostversion",
            old_name="description",
            new_name="description_short",
        ),
        migrations.RemoveField(
            model_name="jobpost",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="jobpost",
            name="version_current",
        ),
        migrations.AddField(
            model_name="jobpostversion",
            name="status",
            field=enumfields.fields.EnumField(
                default="published", enum=eawork.models.post.PostStatus, max_length=255
            ),
        ),
        migrations.AddField(
            model_name="jobpostversion",
            name="description",
            field=TextField(blank=True),
        ),
    ]
