# Generated by Django 3.2.15 on 2022-08-25 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eawork", "0009_change_fields_related"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
