# Generated by Django 3.2.15 on 2022-08-26 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("eawork", "0010_remove_field_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposttag",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
