# Generated by Django 3.2.15 on 2022-08-26 01:04

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("eawork", "0011_fix_field_author_on_job_post_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobalert",
            name="query_string",
            field=models.CharField(blank=True, max_length=1023),
        ),
    ]
