# Generated by Django 3.2.15 on 2022-09-04 02:58

from django.db import migrations
from django.db import models

import eawork.models.job_post
from eawork.models import JobPostTagTypeEnum


def add_tag_types(apps, schema_editor):
    for tag_type in JobPostTagTypeEnum:
        JobPostTagType = apps.get_model("eawork", "JobPostTagType")
        JobPostTagType.objects.get_or_create(type=tag_type)


class Migration(migrations.Migration):

    dependencies = [
        ("eawork", "0015_add_model_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name_plural": "companies"},
        ),
        migrations.AddField(
            model_name="jobpostversion",
            name="tags_exp_required",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={
                    "types__type": eawork.models.job_post.JobPostTagTypeEnum["EXP_REQUIRED"]
                },
                related_name="tags_exp_required",
                to="eawork.JobPostTag",
            ),
        ),
        migrations.RunPython(add_tag_types, migrations.RunPython.noop),
    ]
