# Generated by Django 3.2.15 on 2022-09-11 04:54

from django.db import migrations
from django.db import models

import eawork.models.job_post
from eawork.models import JobPostTagTypeEnum


def add_tag_types(apps, schema_editor):
    for tag_type in JobPostTagTypeEnum:
        JobPostTagType = apps.get_model("eawork", "JobPostTagType")
        JobPostTagType.objects.get_or_create(type=tag_type)


class Migration(migrations.Migration):

    dependencies = [
        ("eawork", "0016_add_field_tags_exp_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpostversion",
            name="tags_location_80k",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={
                    "types__type": eawork.models.job_post.JobPostTagTypeEnum["LOCATION_80K"]
                },
                related_name="tags_location_80k",
                to="eawork.JobPostTag",
            ),
        ),
        migrations.RunPython(add_tag_types, migrations.RunPython.noop),
    ]
