# Generated by Django 3.2.15 on 2022-09-11 04:54

from django.db import migrations
from django.db import models

import eawork.models.job_post


class Migration(migrations.Migration):

    dependencies = [
        ("eawork", "0016_add_field_tags_exp_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpostversion",
            name="tags_location_80k",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={
                    "types__type": eawork.models.job_post.JobPostTagTypeEnum["LOCATION_80K"]
                },
                related_name="tags_location_80k",
                to="eawork.JobPostTag",
            ),
        ),
    ]
