# Generated by Django 3.2.15 on 2022-10-20 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eawork', '0020_add_new_company_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unsubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('too_many_emails', models.BooleanField()),
                ('alerts', models.BooleanField()),
                ('unexpected', models.BooleanField()),
                ('irrelevant', models.BooleanField()),
                ('other_reason', models.TextField(max_length=1000)),
                ('job_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eawork.jobalert')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
