# Generated by Django 3.2.15 on 2022-10-26 16:51

from django.db import migrations


def remote_tag_to_global(apps, schema_editor):
    Alert = apps.get_model("eawork", "JobAlert")
    for alert in Alert.objects.all():
        # if null, move on
        if alert.query_json is None:
            alert.save()
            continue

        # is this an alert for remote jobs?
        includes_remote = False
        for i, sub_arr in enumerate(alert.query_json["facetFilters"]):

            if includes_remote:
                break # we removed the location_type subarr in the inner loop, now move on to updating/adding the tags_country subarr in the next loop
            for key_val_pair in sub_arr:
                if "tags_location_type" in key_val_pair:
                    includes_remote = True
                    del alert.query_json["facetFilters"][i]  # then remove it from the query_json

                    alert.query_string = alert.query_string.replace(
                        "&refinementList%5Btags_location_type%5D%5B0%5D=Remote", ""
                    )  # and remove it from the query_string

        if includes_remote:
            # do we need to update an existing sub_array with tags_country, or do we need to add it?
            isTagsCountry = False

            # we need to update
            for ind, sub_array in enumerate(alert.query_json["facetFilters"]):
                for key_val_pair in sub_array:
                    if "tags_country" in key_val_pair:
                        alert.query_json["facetFilters"][ind].append(
                            "tags_country:Remote, Global"
                        )

                        # this is less crazy than it looks
                        alert.query_string = alert.query_string.replace(
                            "&refinementList%5Btags_country%5D%5B"
                            + str(len(sub_array) - 1)
                            + "%5D=",
                            "refinementList%5Btags_country%5D%5B"
                            + str(len(sub_array) - 1)
                            + "%5D=Remote%2C%20Global&refinementList%5Btags_country%5D%5B"
                            + str(len(sub_array))
                            + "%5D=",
                        )
                        isTagsCountry = True
                        break

            # we need to add it to both
            if not isTagsCountry:
                alert.query_json["facetFilters"].append(["tags_country:Remote, Global"])
                alert.query_string = alert.query_string.replace(
                    "?", "?refinementList%5Btags_country%5D%5B0%5D=Remote%2C%20Global&"
                )

        alert.save()


class Migration(migrations.Migration):

    dependencies = [
        ("eawork", "0022_allow_long_query_strings"),
    ]

    operations = [
        migrations.RunPython(remote_tag_to_global),
    ]
