# Generated by Django 3.2.15 on 2022-11-08 11:38

from django.db import migrations


def huh(subarr):
    if len(subarr) < 1:
        return False

    return True


def become_org_data(apps, schema_editor):
    Alert = apps.get_model("eawork", "JobAlert")

    for alert in Alert.objects.all():
        # if no query, move on
        if alert.query_json is None:
            alert.save()
            continue

        orgs = []
        is_recommended = False
        for sub_arr in alert.query_json["facetFilters"]:

            if len(sub_arr) == 0 or (
                "company_is_recommended_org" not in sub_arr[0]
                and "company_name" not in sub_arr[0]
            ):
                continue  # skip non org tags

            if "company_is_recommended_org" in sub_arr[0]:
                uhh = [sub_arr.pop(0) for item in list(sub_arr)]  # time, money, etc
                is_recommended = True
            elif "company_name" in sub_arr[0]:
                more_orgs = [sub_arr.pop(0) for item in list(sub_arr)]
                orgs = orgs + more_orgs

        # remove empties
        alert.query_json["facetFilters"] = list(filter(huh, alert.query_json["facetFilters"]))

        # combine
        if is_recommended:
            orgs.append("org_data:is_recommended_org")

        # rename
        orgs = list(
            map(
                lambda entry: entry.replace("company_name", "org_data"),
                orgs,
            )
        )

        # assign
        if len(orgs):
            alert.query_json["facetFilters"].append(orgs)

        alert.save()


def reverse(apps, schema_editor):
    print("reversed")


class Migration(migrations.Migration):

    dependencies = [
        ("eawork", "0026_auto_20221107_1241"),
    ]

    operations = [
        migrations.RunPython(become_org_data, reverse_code=reverse),
    ]
