# Generated by Django 3.2.15 on 2022-11-25 18:37

from django.db import migrations, models
import eawork.models.tag


class Migration(migrations.Migration):

    dependencies = [
        ('eawork', '0029_auto_20221123_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tags_areas',
            field=models.ManyToManyField(blank=True, limit_choices_to={'types__type': eawork.models.tag.JobPostTagTypeEnum['AREA']}, related_name='tags_areas', to='eawork.JobPostTag'),
        ),
        migrations.AddField(
            model_name='company',
            name='tags_locations',
            field=models.ManyToManyField(blank=True, limit_choices_to={'types__type': eawork.models.tag.JobPostTagTypeEnum['LOCATION_80K']}, related_name='tags_locations', to='eawork.JobPostTag'),
        ),
        migrations.AddField(
            model_name='company',
            name='text_hover',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobpostversion',
            name='salary',
            field=models.TextField(blank=True),
        ),
    ]
