# Generated by Django 3.2.15 on 2022-12-08 17:34

from django.db import migrations, models
import eawork.models.tag


class Migration(migrations.Migration):

    dependencies = [
        ('eawork', '0030_auto_20221125_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='glassdoor_url',
            field=models.URLField(blank=True, max_length=511, verbose_name='Glassdoor'),
        ),
        migrations.AddField(
            model_name='company',
            name='org_size',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='social_media_links',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='yearFounded',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobpostversion',
            name='recently_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobpostversion',
            name='tags_area_filter',
            field=models.ManyToManyField(blank=True, limit_choices_to={'types__type': eawork.models.tag.JobPostTagTypeEnum['AREA']}, related_name='tags_area_filter', to='eawork.JobPostTag'),
        ),
    ]
