# Generated by Django 3.2.16 on 2023-01-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eawork', '0033_auto_20221208_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description_short',
            field=models.TextField(blank=True),
        ),
    ]
