# Generated by Django 3.2.16 on 2023-01-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eawork', '0034_company_description_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='additional_commentary',
            field=models.TextField(blank=True),
        ),
    ]
