# Generated by Django 3.2.16 on 2023-01-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eawork', '0035_company_additional_commentary'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostversion',
            name='evergreen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobpostversion',
            name='visa_sponsorship',
            field=models.TextField(blank=True),
        ),
    ]
