# Generated by Django 3.2.16 on 2023-01-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eawork', '0036_auto_20230119_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposttag',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
