databases:
  - name: eawork
    databaseName: eawork
    user: eawork

services:
  - type: web
    name: eawork
    env: python
    buildCommand: poetry install && python manage.py collectstatic --no-input && python manage.py migrate
    startCommand: gunicorn eawork.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: eawork
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
  - type: cron
    name: 80'000h import
    env: python
    schedule: "0 6 * * *"
    buildCommand: poetry install
    startCommand: python manage.py import_80_000_hours && python manage.py check_new_jobs_for_all_alerts
