databases:
  - name: eawork-database
    databaseName: eawork
    user: eawork

services:
  - type: web
    name: eawork-web
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn eawork.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: eawork
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
  - type: redis
    name: eawork-redis
    plan: starter
    maxmemoryPolicy: noeviction
    ipAllowList: [] # only allow internal connections
  - type: worker
    name: eawork-celery
    env: python
    buildCommand: ./build.sh
    startCommand: celery --app tasks worker --loglevel info --concurrency 4
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString
